### ISSUE TITLE
gcp-ns.py fails if project.name is empty

### ISSUE THREAD

**Issue by ramshazar** [ovotech/domain-protect-gcp#7]
The script manual-scans/gcp-ns.py fails if a project name is empty (or non existing?). I did not check the other scripts yet.

```
Traceback (most recent call last):
  File "/tmp/scanner/manual-scans/gcp-ns.py", line 98, in <module>
    gcp(project.name)
  File "/tmp/scanner/manual-scans/gcp-ns.py", line 137, in __init__
    print("Searching for Google Cloud DNS hosted zones in " + project + " project")
TypeError: can only concatenate str (not "NoneType") to str
```

It is somehow possible to have a GCP project with an empty project name. 
I do not know a way to reproduce that. GCP console does not accept an empty name, gcloud uses project id as project name if project name is empty.

Is there a specific reason why you chose to use project.name instead of project.project_id here: https://github.com/ovotech/domain-protect-gcp/blob/dev/manual-scans/gcp-ns.py#L137
For me it works if I use project.project_id instead of project.name.

Maybe that this is a very weird edge case that may not be worth a fix.

**Comment by paulschwarzenberger** [comment]
Thanks for raising the issue @ramshazar, I chose project name to pass to the function, because I felt it would be more informative in the screen output (and Function logs in the case of the automated scans). 

Have you considered adding a Project Name to that GCP project, in Project Settings?

**Comment by paulschwarzenberger** [comment]
Closing this, as a Project Name should be given to all GCP projects
